In [13]:
import numpy as np

p = np.array([[1, 7], [2, 1], [3, 2]])
q = np.array([[1, 1], [1, -1], [1, 0]])

[[1 7]
 [2 1]
 [3 2]]


> Addition

In [8]:
c1 = np.add(p, q)
print(c1)

[[2 8]
 [3 0]
 [4 2]]


> Substraction

In [10]:
c2 = np.subtract(p, q)
print(c2)

[[0 6]
 [1 2]
 [2 2]]


> Multiplication

In [12]:
c3 = np.multiply(p, q)
print(c3)

[[ 1  7]
 [ 2 -1]
 [ 3  0]]


> Dot product

In [16]:
r=np.array([[1, 3, 1], [1, 0, 1]])
cdot = np.dot(p, r)
print(cdot)

[[8 3 8]
 [3 6 3]
 [5 9 5]]


> Determinant

In [18]:
det = np.linalg.det(cdot)
print(det)

0.0


> Inverse

In [20]:
m=np.array([[1, -1], [2, 3]])
inverse=np.linalg.inv(m)
print(inverse)

[[ 0.6  0.2]
 [-0.4  0.2]]
