# Vector Implementation


In [1]:
import numpy as np

v = np.array([1, -1, 2])
w = np.array([2, 5, 2])

In [4]:
print(v+w)
print(v-w)
print(v*w)

[3 4 4]
[-1 -6  0]
[ 2 -5  4]


### Getting the length of the vector:

In [8]:
print(np.linalg.norm(v))

2.449489742783178


### Dot Product

In [6]:
print(np.dot(v, w))

1
